title: Hanyu Gao
# tagline: Here is personal website of Hanyu Gao. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://hanyugaox.github.io/

# Owner/author information
owner:
  name: Hanyu Gao
  avatar: hanyu.jpg
  # bio: Two roads diverged in woods, I took the one less traveled by.
  email: henrygao@zju.edu.cn
  cv: https://github.com/HanyuGaoX/HanyuGaoX.github.io/file/CV-Hanyugao.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter:
  github: HanyuGaoX
  # linkedin:
  scholar: https://scholar.google.com/citations?user=U1OPi1YAAAAJ
  # bilibili: 
  researchgate: https://www.researchgate.net/profile/Hanyu-Gao-4
  # zhihu:
  # facebook:
  # instagram:
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: Projects
    url: /projects/
  - title: Hobbies
    url: /hobbies/
  - title: Blogs
    url: /blogs/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: hanyugao

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2024/2/17 by Hanyu Gao.